language: cpp
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    packages:
    - cmake-data
    - cmake
    - gcc-5
    - g++-5
env:
- COMPONENT=game-server
script: ci/script.sh
notifications:
  email: false
  slack:
    secure: JW03tkKPkoIXkqjvqKWTbjFinyhUUZIrtW/snG4PlSmNjA49l0QUGtuKXhYjXorF1roGUan54wkJJCqr8GNx3HkwQVYWN8xFHlzk64iC/JSzIvUrcqrKBpz9nxQXIPHT5wGymFemcSaX3zvaI4qLtONPSIHS1QkOxy/rqPN3u7GpsWV5CzoUkXgFCGBr2kujZlAAD6l1w7wmcGI4fWKVoauHuvLUmax+gKmniA60+jX3gH2ppztwC9fizD29Li4ECz/FAHk1qfLEnmUuKt57lBR0Rho5hoOA+vPlIDHSHcY10aYMO6IezWXPWrQ1dzKNMw7xuFbYXwFwIHtERUCcWtnYj/3zNApAR2dj2IGIC365HlNRQsJwhz8O+YEGKmXUFLwWEyXclmBgy2LBw84EVMtl2C+PpJkSwnDEZScVrUwvcPllCISG+zmidqB4cMLbjgi/EpB+gLXisUvBuWIEqWQ+j3XaNBaEkqff9zYMUt/rjpQfuKzaZW+cTpqcljE974gbTDA278Mk4j0nxim+60L5PLjiWXCe4txUIAIn8G3+Tqfsus25B+m+RZUWT8XFE7wWfubBZ2p2gD4nu070eVUaBMQ/G/LlzMNFxFiKEH+rlZJksfF7l1P7ObCfeu+UNG1aKNF9q3r4zXVYcOwkZIpYawsjbCVd4deKn8vLLqw=
