language: cpp
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    packages:
    - cmake-data
    - cmake
    - gcc-5
    - g++-5
env:
- COMPONENT=game-server
script: ci/script.sh
notifications:
  email: false
  slack:
    secure: vu6E05bgteY3941BdH9pwNMBya63kft4ApBpp2/t+5pWSudK1m0/fEjfZS2puv/cPo640Tgi+NSBmSrY2gRpe2xBaOu+AElNY+53A/iznkvQlWoEVv+so3x6E83z5wMF0GzafBKOuF6z+pP4KVzHmkVwcdkAwpJ9XX0I+osfAKHsAD7MWGqm8LTl9v17ee0cqTBYKkvgMuQU5YxAbuf5zLsREslXbcU/2eSOrTc0A21Rmcw+EBVGnTIOdvmlNkOklGi+oq3sPdm+7fi2A5bXf4Dhfk0uWgllNaCrhH3Skqg25W/pEbnFHOuJPwFBtxs8BOZn/qsvz7WxyfD3N99PO/yxkb/wsZloJ8T6veOhslZaoCUbQnrXkF+64lrBfnvPqdPiZJVB6nh28TGuYtOXDr1YEU9Fp3GF70i+mxe1LLGVRhSqULR9HtKGtZkMcxeca4zIgC8GJxGyWHPqlY85KxuGCrFThsh8PrmVbswUexj72k3u7KmEaKQS2a301QdF6Ez/rd7erCG9Lvn3EHC/N+iztDzRRIujcBFZdU/k8VDC9zU3hNYeGEl6VGkmbFBI5sxQcebUVY80dxjdM5pNoXdqC6r5ZXxW3UbhveIHX5ELvThUCLT+OpEe1O68t8SjNbpCDuNX7U9PXpvJVXz50d4boPbeeE3ZwzXpjpve/uA=
